# Generated by Django 3.2 on 2021-04-29 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id_bus', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_bus', models.CharField(max_length=40)),
                ('img_front_bus', models.CharField(max_length=15)),
                ('icon_bus', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('Time_start', models.CharField(max_length=5)),
                ('Time_end', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Bus_stop',
            fields=[
                ('id_busstop', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_busstop', models.CharField(max_length=80)),
                ('latitude_busstop', models.FloatField()),
                ('longitude_busstop', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rout',
            fields=[
                ('id_rout', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_bus', models.ForeignKey(db_column='id_bus', on_delete=django.db.models.deletion.CASCADE, to='blogs.bus')),
                ('id_busstop', models.ForeignKey(db_column='id_busstop', on_delete=django.db.models.deletion.CASCADE, to='blogs.bus_stop')),
            ],
        ),
    ]
