# Generated by Django 3.2 on 2021-08-12 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bus',
            table='Bus',
        ),
        migrations.AlterModelTable(
            name='bus_stop',
            table='Bus_stop',
        ),
        migrations.AlterModelTable(
            name='rout',
            table='Rout',
        ),
        migrations.CreateModel(
            name='Graph_busstop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('busstop_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busstop_a', to='blogs.bus_stop')),
                ('busstop_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busstop_b', to='blogs.bus_stop')),
            ],
            options={
                'db_table': 'Graph_busstop',
            },
        ),
    ]
